### ISSUE TITLE
Required Sec-WebSocket-Protocol

### ISSUE THREAD

**Issue by winternet-studio** [Textalk/websocket-php#110]
I had a server connection which ending up with the exception `Connection to '{$address}' failed: Server sent invalid upgrade response: {$response}`. Server was made with Microsoft-HTTPAPI/2.0. I found it required the header `Sec-WebSocket-Protocol` - then it worked fine. The browser automatically adds this header, so shouldn't this library do the same? Otherwise I think it's important to note in the docs that this header could be crucial...

**Comment by sirn-se** [comment]
The error you experience is application level, the service you're trying to use is requiring a certain subprotocol. A subprotocol is defined by the optional Sec-WebSocket-Protocol header, possible values here: https://www.iana.org/assignments/websocket/websocket.xml#subprotocol-name

This library is lower level, implementing the websocket protocol itself. It can not and should not make assumptions concerning content format. Implementing a client specific for a certain subprotocol can of course be built on top of this library.

How to set Sec-WebSocket-Protocol header is mentioned in the documentation: https://github.com/Textalk/websocket-php/blob/master/docs/Client.md#constructor-options
