### ISSUE TITLE
stream_socket_get_name() requires two arguments on my version of PHP (7.4.3 )

### ISSUE THREAD

**Issue by andywise0** [Textalk/websocket-php#130]
Calling $client->getName() causes the script to fail - the error message reports stream_socket_get_name() requires two arguments 

**How to reproduce**
Using Ubuntu / PHP 7.4.3 (Laravel environment)
$client = new Client($options['uri'], $options);
$client->getName();

Observe error

**Logs**
No logs.

**Versions**
* Version of this library - just dowloaded it
* PHP version 7.4.3

Fix is to change line 150 of Base.php from:
return $this->isConnected() ? stream_socket_get_name($this->socket) : null;
to
return $this->isConnected() ? stream_socket_get_name($this->socket, false) : null;

Library working fine for me now I've made that change.

**Comment by sirn-se** [comment]
Thanks. Fixing and deploying new version later today.

**Comment by sirn-se** [comment]
Fixed in `1.5.2`.
