### ISSUE TITLE
when send payload  happend  errorMessage : Could only write 0 out of 15 bytes

### ISSUE THREAD

**Issue by Maoxp** [Textalk/websocket-php#135]
**Describe the bug**
When I connect websocket for a period of time and estimate a few minutes, the following error appears
`{"message":"Could only write 0 out of 15 bytes.","code":0,"line":473,"file":"/home/www-data/workSpace/iot-mattress/vendor/textalk/websocket/lib/Base.php"}
`
I just sent a ping

**Versions**
* Version of this library
"textalk/websocket": "^1.5"
* PHP version
 PHP7.3

**Comment by sirn-se** [comment]
This error typically indicates that the underlying connection has become unavailable. Without additional information it is not possible to be more specific than that.

Short version, this can happen and need to be handled by calling code. See Client documentation for some pointers;
https://github.com/Textalk/websocket-php/blob/master/docs/Client.md#listening-to-a-server

If you need further information of the error, you can set up a logger. More info on that here;
https://github.com/Textalk/websocket-php/blob/master/docs/Examples.md#echo-logger

**Comment by Maoxp** [comment]
> This error typically indicates that the underlying connection has become unavailable. Without additional information it is not possible to be more specific than that.
> 
> 
> 
> Short version, this can happen and need to be handled by calling code. See Client documentation for some pointers;
> 
> https://github.com/Textalk/websocket-php/blob/master/docs/Client.md#listening-to-a-server
> 
> 
> 
> If you need further information of the error, you can set up a logger. More info on that here;
> 
> https://github.com/Textalk/websocket-php/blob/master/docs/Examples.md#echo-logger

thank you，i try again

**Comment by sirn-se** [comment]
Inactive, closing
