### ISSUE TITLE
Don't close the connection if client timeout while reading

### ISSUE THREAD

**Issue by marcroberts** [Textalk/websocket-php#139]
The `timed_out` value from `stream_get_meta_data()` is used to determine which exception to throw in the Base.php [throwException()](https://github.com/Textalk/websocket-php/blob/62bc84e75f6d244f81bdeee2fda3d5c39880cc99/lib/Base.php#L468) function. But this is after the connection has already been closed.

This could be used earlier in the `read()` function to throw the exception without closing the connection, allowing us to attempt a `receive()` for {timeout} seconds and if no data received, send a ping to keeping the connection open rather than forcing a reconnection.

I'm happy to create a PR for this if you'd accept this (maybe behind an option, `keep_open_on_timeout`?)

**Comment by sirn-se** [comment]
Released as version `1.5.4`.
