### ISSUE TITLE
External error handling

### ISSUE THREAD

**Issue by alfio8788** [Textalk/websocket-php#143]
I have this part of code:

`try{
        $this->_connection = new WebSocket\Client('ws://127.0.0.1:8080');
        $this->_isConnected = true;
}catch(exception $e){
        $this->_isConnected = false;
}`

When the client is unable to connect (my websocket server goes down, i reboot it or similar) i am being thrown the exception "connection refused" but the error does not come from my code, so i am unable to catch it (i want to continue execution anyway as the client only notifies some events to simplify moderation (new comment, new forum post or thread as examples) in our site, in other words nothing too important is going to break if the websocket server goes down for a minute or 2).

Now the question: is it possible to bypass / manage on my side the errors without editing the code of the client or do i have to keep a fork of it and edit it wherever needed?

**Comment by alfio8788** [comment]
This is the error i am being shown:

> Uncaught Exception: Could not open socket to "127.0.0.1:8080": Connection refused (111) stream_socket_client(): unable to connect to tcp://127.0.0.1:8080 (Connection refused).

I tried changing it to catch(WebSocket\ConnectionException) but nothing changes

**Comment by sirn-se** [comment]
@alfio8788 The client applies "lazy" connecting - it do not actually connect until you attempt to use it for read or write.

So in order to catch exceptions, it is the code using the client that need to go into a try/catch block. The constructor itself will never cause exception.
