### ISSUE TITLE
Connection with WSS

### ISSUE THREAD

**Issue by alfonsotesone** [Textalk/websocket-php#159]
Hi, first of all, thank you for your work!

I have a question about the WSS. Is it possible to use the library to connect to WebSockets with ssl? If I add "wss: //mywebsockethost.com" instead of "ws://mywebsockethost.com" on the initialization of the variable the connection to the websocket fails. Can you give me some suggestions? 

Thank you again!

**Comment by sirn-se** [comment]
Yes, it does support `wss` over `ssl`.

Hard to tell without error message or logs, but a common issue has been related to certificate verification.
You can test by disabling the peer verification, as described here:
https://github.com/Textalk/websocket-php/blob/master/docs/Client.md#constructor-options

```php
$context = stream_context_create();
stream_context_set_option($context, 'ssl', 'verify_peer', false);
stream_context_set_option($context, 'ssl', 'verify_peer_name', false);

$client = new WebSocket\Client("wss://mywebsockethost.com/", [
    'context' => $context, // Attach stream context created above
]);
```

Note that disabling verification reduces security. Fine for testing, but a production server should support this.

**Comment by alfonsotesone** [comment]
> Yes, it does support `wss` over `ssl`.
> 
> Hard to tell without error message or logs, but a common issue has been related to certificate verification. You can test by disabling the peer verification, as described here: https://github.com/Textalk/websocket-php/blob/master/docs/Client.md#constructor-options
> 
> ```
> $context = stream_context_create();
> stream_context_set_option($context, 'ssl', 'verify_peer', false);
> stream_context_set_option($context, 'ssl', 'verify_peer_name', false);
> 
> $client = new WebSocket\Client("wss://mywebsockethost.com/", [
>     'context' => $context, // Attach stream context created above
> ]);
> ```
> 
> Note that disabling verification reduces security. Fine for testing, but a production server should support this.

Thank you for your fast answer and for your support!

When I disabling the peer verification works well, with the peer verification enabled I have this error:
`Could not open socket to \"mywebsockethost.com:port\":  (0) stream_socket_client(): Unable to connect to ssl://mywebsockethost.com:port (Unknown error).`
