### ISSUE TITLE
How can I use this package with laravel?

### ISSUE THREAD

**Issue by omer-ayhan** [Textalk/websocket-php#162]
**Describe your issue**
Is there way to use this composer package with laravel framework?

**Comment by RezaParsian** [comment]
@omer-ayhan hey bro.

its so easy just install that with composer.
```
composer require textalk/websocket
```

then in your controller or anything else you like

type

```
$client = new WebSocket\Client("SocketAddress");
```

its done.
enjoy 🤘

**Comment by ayzeecheema** [comment]
> @omer-ayhan hey bro.
> 
> its so easy just install that with composer.
> 
> ```
> composer require textalk/websocket
> ```
> 
> then in your controller or anything else you like
> 
> type
> 
> ```
> $client = new WebSocket\Client("SocketAddress");
> ```
> 
> its done. enjoy 🤘

1) DO I need to setup the websocket server first and then install this package? or just create a new project and install this package and it will set up the socket server itself?
2) Is there any demo video of how to use this package step by step?
3) Lets say I have installed this package, which files or piece of code to change ?
Currently in my project, I have my socketserver ready and have this package installed. When I connect it with Socket Server Test Client extension, it shows the connection is established. But when I send a message in request, it gives the following error
"exception-errorexception-thrown-attempt-to-read-property-event-on-null anyID: exception ErrorException thrown: Attempt to read property "event" on null."
![image](https://user-images.githubusercontent.com/100202016/170684094-c5404cb9-897f-4cad-9fd1-f8da2b760c98.png)

**Comment by RezaParsian** [comment]
@ayzeecheema i dont no there is any video or not.
i use client version only.

**Comment by omer-ayhan** [comment]
> 

I actually want to use it inside another websocket, is this possible?

**Comment by sirn-se** [comment]
@omer-ayhan 

Not sure what you mean with using this websocket in another websocket.

You can use it in your own code, as @RezaParsian suggests, regardless of Laravel.
You should also be able to replace the Laravel websocket implementation with this, but that would require changing the Laravel code so I would not recommend it.

**Comment by sirn-se** [comment]
@ayzeecheema

This repo provides functions to send and receive websocket messages, the functional implementation is up to you.
You can use this example to start with; https://github.com/Textalk/websocket-php/blob/master/examples/echoserver.php

The error in your screen dump is **not** caused by code in this repo, so you need to figure that out yourself.

**Comment by omer-ayhan** [comment]
> @omer-ayhan
> 
> Not sure what you mean with using this websocket in another websocket.
> 
> You can use it in your own code, as @RezaParsian suggests, regardless of Laravel. You should also be able to replace the Laravel websocket implementation with this, but that would require changing the Laravel code so I would not recommend it.

What I mean by that, is there a possiblity to receive websocket messages while being inside another websocket in laravel and sending them to client again, it's simple like nested websockets. My purpose on that is to hide my websocket adress.

**Comment by sirn-se** [comment]
I suppose you could build some proxy function, receiving messages from one connection and propagating them onto another connection. So yes, you could use this as a client in such setup. There's no conflict, except that each server need to listen do different sockets.
