### ISSUE TITLE
Upgrade psr/http-message to ^1.1 || ^2.0

### ISSUE THREAD

**Issue by mashb1t** [Textalk/websocket-php#184]
**Is it within the scope of this library?**
Yes, usage of dependency in composer modules.

**Describe the solution you'd like**
[Release 2.0](https://github.com/php-fig/http-message/releases/tag/2.0) is available and includes return types (see [here](https://www.php-fig.org/psr/psr-7/meta/#72-type-additions)).

Currently psr/http-message is locked at ^1.0 [here](https://github.com/Textalk/websocket-php/blob/master/composer.json#L29C24-L29C24).
Does this have a specific reason or would it be possible to upgrade to `"^1.0 || ^2.0"`?

**Comment by sirn-se** [comment]
Hello @mashb1t 

I'm continuing development of this [library](https://github.com/sirn-se/websocket-php/tree/master) as `phrity/websocket`. 

Version `1.7` support `^1.0 | ^2.0` of `psr/http-message`.

**Comment by mashb1t** [comment]
Hey @sirn-se,

thank you for the update, will use your repository then instead. Maybe it would be even more obvious for non-involved users if you could add a reference / deprecation note to the project README (if this is the case).

**Comment by sirn-se** [comment]
@mashb1t Unfortunately I no longer have access to this GitHub account. That's why I had to move it to begin with.
