### ISSUE TITLE
Exception with ratchet server

### ISSUE THREAD

**Issue by Ducatel** [Textalk/websocket-php#19]
Hello,

I have a crash when I try to connect with a ratchet server (dev-master version).

    Fatal error: Uncaught exception 'WebSocket\ConnectionException' with message 'Connection to 'ws://192.168.56.101/test/-1' failed: Server sent invalid upgrade response:
    HTTP/1.1 101 Switching Protocols

My client code:

    $wsclient = new Client("ws://192.168.56.101:4242/test/-1");
    $arrayToSend = [
			'id' => $archiveId,
			'status' => 0
	];
	$wsclient->send(json_encode($arrayToSend));

My ratchet server code:

    $app = new Ratchet\App('192.168.56.101', 4242, '0.0.0.0');
    $app->route('/test/{id}', new CommonDashboard\webSocket\TestWebSocket(), array('*'));
    $app->run();

Do you have any ideas for fixing that ?
Thank ;)

**Comment by fiddur** [comment]
I haven't tried ratchet.  This failure would come if the server doesn't include "sec-websocket-accept" in the response header.  Could you try dumping $response in Client.php:126?

According to WebSocket specification:

       If the response lacks a |Sec-WebSocket-Accept| header field or
       the |Sec-WebSocket-Accept| contains a value other than the
       base64-encoded SHA-1 of the concatenation of the |Sec-WebSocket-
       Key| (as a string, not base64-decoded) with the string "258EAFA5-
       E914-47DA-95CA-C5AB0DC85B11" but ignoring any leading and
       trailing whitespace, the client MUST _Fail the WebSocket
       Connection_.

**Comment by Ducatel** [comment]
I cannot dumping object in line 126 (The exception is throw in line 121)

So the var_dump in `textalk\websocket\lib\client:116`

    string(33) "HTTP/1.1 101 Switching Protocols
	"

	Fatal error: Uncaught exception 'WebSocket\ConnectionException' with message 'Connection to 'ws://192.168.56.101/unarchive/-1' failed: Server sent invalid upgrade response:
	HTTP/1.1 101 Switching Protocols
	' in /var/www/default/vendor/textalk/websocket/lib/Client.php:124
	Stack trace:
	#0 /var/www/default/vendor/textalk/websocket/lib/Base.php(30): WebSocket\Client->connect()
	#1 /var/www/default/WebSocketAPI/Consumer/UnarchiveConsumer.php(93): WebSocket\Base->send()
	#2 /var/www/default/WebSocketAPI/Consumer/UnarchiveConsumer.php(73): UnarchiveConsumer->sendAck()
	#3 /var/www/default/WebSocketAPI/Consumer/UnarchiveConsumer.php(53): UnarchiveConsumer->callback()
	#4 (): {closure}()
	#5 /var/www/default/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(972): call_user_func()
	#6 (): PhpAmqpLib\Channel\AMQPChannel->basic_deliver()
	#7 /var/www/default/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(173): call_user_func()
	#8 /var/www/default/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(362): PhpAmqpLib\Channel\AbstractChannel->dispatch()
	#9 /var/www/default/WebSocketAPI/Consumer/UnarchiveConsumer.php(56): PhpAmqpLib\Channel\AbstractChannel->wait()
	#10 /var/www/default/WebSocketAPI/Consumer/UnarchiveConsumer.php(104): UnarchiveConsumer->listen()
	#11 {main}

**Comment by fiddur** [comment]
That's weird, no headers in the response.  It could be a broken package that isn't completely read, or the server isn't sending it completely.  I thought I went through all the hoops to make sure I got the complete response…  Can you see what ratchet actually sends on the other end, or some tcpdump?

From what I can see in ratchet it should at least set the header `X-Powered-By`.
https://github.com/ratchetphp/Ratchet/blob/master/src/Ratchet/WebSocket/WsServer.php#L125

**Comment by Ducatel** [comment]
When I use FireFox, I have this response header:

	Connection: Upgrade
	Sec-WebSocket-Accept: /AX6WF2wCFydrlnjMoc5FE+N6zw=
	Upgrade: websocket
	X-Powered-By: Ratchet/0.3.2

On Chrome:
	HTTP/1.1 101 Switching Protocols
	Upgrade: websocket
	Connection: Upgrade
	Sec-WebSocket-Accept: GCFuC3AxgIzUDWwRpglrj7YDUsE=
	X-Powered-By: Ratchet/0.3.2

So the header seem complete.

**Comment by fiddur** [comment]
Ok, looks like the communication is broken.  I think that instead of just reading the packet until eof or unread_bytes == 0, it should try to read (with a timeout) until it gets end of header marker, in other words the double CR+LF.

I'll try to reproduce it when I get some time but it probably wont be today…

**Comment by Ducatel** [comment]
If I remove the optional parameter in client:109 like

	$response = '';
	do {
		$buffer = stream_get_line($this->socket, 1024); // here, I remove the optional arg
		$response .= $buffer . "\n";
		$metadata = stream_get_meta_data($this->socket);
		var_dump($buffer);
	} while (!feof($this->socket) && $metadata['unread_bytes'] > 0);

I have the complete header.
So the var_dump of `$buffer`

	string(158) "HTTP/1.1 101 Switching Protocols
	Upgrade: websocket
	Connection: Upgrade
	Sec-WebSocket-Accept: XjUqtU/wQOS6XGlyiPSdqZ5h6jY=
	X-Powered-By: Ratchet/0.3.2

	"

**Comment by fiddur** [comment]
Nice debugging.  I'll make some experiments with this; we need to be sure that we don't read too much.  There *could* be a websocket frame directly after the header, so I think we must check for the double line breaks.

**Comment by fiddur** [comment]
I'm sorry for not getting back to you sooner.

Could you try the branch `devHeaderEnding` and see if it works better?

**Comment by Nepoxx** [comment]
@fiddur It resolved the issue for me!
