### ISSUE TITLE
This library is prepared for node.js server?

### ISSUE THREAD

**Issue by matak** [Textalk/websocket-php#29]
I am trying to send something to node.js socket.io running server, but no chance.

``` php
php index.php

Fatal error: Uncaught exception 'WebSocket\ConnectionException' with message 'Connection to 'ws://localhost/' failed: Se
rver sent invalid upgrade response:
' in X:\srv\git.romanmatena.cz\solis5-advanced\websocket-php-client\vendor\textalk\websocket\lib\Client.php:149
Stack trace:
#0 X:\srv\git.romanmatena.cz\solis5-advanced\websocket-php-client\vendor\textalk\websocket\lib\Base.php(48): WebSocket\C
lient->connect()
#1 X:\srv\git.romanmatena.cz\solis5-advanced\websocket-php-client\index.php(10): WebSocket\Base->send('Hello WebSocket..
.')
#2 {main}
  thrown in X:\srv\git.romanmatena.cz\solis5-advanced\websocket-php-client\vendor\textalk\websocket\lib\Client.php on li
ne 149
```

**Comment by fiddur** [comment]
I haven't tried it, but this client should handle any correct implementation of the protocol.  If you could point out more precisely what is wrong and make sure socket.io handles it correctly…  I don't have time right now to setup my own test for it.

**Comment by trogper** [comment]
I've added protocol support to Client.php
It was rather simple. Please, create a pull request of it, if you can.
I've added a parameter for Client constructor, so now you call
new Client("ws://localhost:9124", "echo-protocol");

Client.php.diff
`15d14
<   protected $protocol;
25c24
<   public function __construct($uri, $protocol, $options = array()) {
---
>   public function __construct($uri, $options = array()) {
34d32
< 	$this->protocol = $protocol;
49d46
<     $protocol  = $this->protocol;
111,117c108,113
<       'host'                   => $host . ":" . $port,
<       'user-agent'             => 'websocket-client-php',
<       'connection'             => 'Upgrade',
<       'upgrade'                => 'websocket',
<       'sec-websocket-key'      => $key,
<       'sec-websocket-protocol' => $protocol,
<       'sec-websocket-version'  => '13',
---
>       'host'                  => $host . ":" . $port,
>       'user-agent'            => 'websocket-client-php',
>       'connection'            => 'Upgrade',
>       'upgrade'               => 'websocket',
>       'sec-websocket-key'     => $key,
>       'sec-websocket-version' => '13',
`

**Comment by Enelar** [comment]
@trogper thanks for participation, i will PR it later

**Comment by sirn-se** [comment]
If the optional protocol specifier is the issue, the Client already support it in the option array.
```php
$client = new Client($url, ["headers" => ["sec-websocket-protocol" => "echo-protocol"]]);
```

Closing this.
