### ISSUE TITLE
WSS connection fails on OpenWRT with Linux 4 Kernel and PHP 5.6.16

### ISSUE THREAD

**Issue by richardklingler** [Textalk/websocket-php#34]
Client works perfectly on OpenWRT with Linux Kernel 3.10.49 and PHP 5.4.38.

But fails when upgraded to Linux 4.1.13 and PHP 5.6.16 on OpenWRT with:

Fatal error: Uncaught exception 'WebSocket\ConnectionException' with message 'Could not open socket to "myserver.com:443":  (0).' in /www/ws/lib/Client.php:65
Stack trace:
#0 /www/ws/lib/Base.php(122): WebSocket\Client->connect()
#1 /www/ws/wsclient.php(38): WebSocket\Base->receive()
#2 {main}
  thrown in /www/ws/lib/Client.php on line 65

Runs fine though on Ubuntu with Kernel 3.16.7 and PHP 5.6.20.

**Comment by fiddur** [comment]
Weird, it fails on the native `stream_socker_client` then; sounds like an error in that PHP compilation.

Have you tried removing the `@` on https://github.com/Textalk/websocket-php/blob/master/lib/Client.php#L85

Should give the same error info, but you never know with PHP…

**Comment by richardklingler** [comment]
Hello

Sorry for late reply...long time not logged into github (o;

Found the reason now why the connection failed....seems to be OpenWRT specific...

Besides the /etc/certs/* files I had on the module...I needed to also install the OpenWRT package "ca-certificates".....

Now all runs smoothly again ;-)

**Comment by fiddur** [comment]
Ok, great :)
