### ISSUE TITLE
Using a http proxy server to connect

### ISSUE THREAD

**Issue by tivotyro** [Textalk/websocket-php#35]
Is there any way to cause a Client to connect() via an HTTP Proxy with authentication?

**Comment by Enelar** [comment]
@tivotyro no. Do you have HTTP proxy that offers WebSocket pass-through?
I am just trying to understand, at the scale 1 to 10, how much this feature is demanding.

**Comment by dopoln** [comment]
Is there any way to cause a Client to connect() via an SOCKS5 Proxy with authentication?
Scale 10 !!!  Please)
