### ISSUE TITLE
WAMP sub-protocol

### ISSUE THREAD

**Issue by bkdotcom** [Textalk/websocket-php#36]
FYI / "Feature Request"

Found textalk/websocket-php when searching for a WAMP client that didn't have stacks and stacks of dependencies and are only meant to be incorporated in command-line scripts.

By using texttalk/websocket-php and performing a simple little handshake on connection I was able to build a basic WAMP client for the single purpose of for pushing "messages"/data to a WAMP server.
(I have no need for "subscribing" to WAMP topics or remote procedure calls)

https://github.com/bkdotcom/WampPublisher

Feel free to borrow/incorporate it into this project.

**Comment by fiddur** [comment]
Nice.  It's better to have as a subproject and not incorporated.  Perhaps it could be added in the README as a reference…
