### ISSUE TITLE
PHP7 Support

### ISSUE THREAD

**Issue by Roycohen** [Textalk/websocket-php#39]
It seems like there is no support in PHP7.
Am I'm missing something.

**Comment by Enelar** [comment]
@Roycohen i am successfully running at 7.1

**Comment by Enelar** [comment]
@fiddur Can we add travis test on 7.0 as well?

**Comment by Roycohen** [comment]
Try with wss.
Working in secure mode.

**Comment by MarkHerhold** [comment]
PR for testing 7.0, 7.1 with Travis passes: https://github.com/Textalk/websocket-php/pull/51

**Comment by sirn-se** [comment]
Added Travis support up to PHP 7.4

https://github.com/Textalk/websocket-php/pull/72
