### ISSUE TITLE
Subscribe

### ISSUE THREAD

**Issue by sinasalek** [Textalk/websocket-php#40]
Is it possible to subscribe to a channel via this library ?

**Comment by Enelar** [comment]
@sinasalek what do you mean?
WebSocket is quite similar to regular [sockets](https://en.wikipedia.org/wiki/Network_socket). They do not have such method.

I am suppose you talking about some framework, which is using 'channels' metaphor.

**Comment by sinasalek** [comment]
Not a framework, a protocol. http://wamp-proto.org/implementations/
There are many implementations for it, i use http://autobahn.ws/js/
Publisher and Subscriber are the features of WAMP protocol.
I wanted to connect to my wamp socket server and subscribe to a channel.
The connection part works just fine but currently it's not possible to be notified when a particular channel updates

**Comment by Enelar** [comment]
@sinasalek no, this library provides WebSockets only.
Horewer official WAMP site offers this solutions:
https://github.com/voryx/Thruway
https://github.com/Vinelab/minion

Please return and say which was better :)

**Comment by sinasalek** [comment]
Awesome, tx :)
