### ISSUE TITLE
Headers are slightly wrong, but easy to fix

### ISSUE THREAD

**Issue by christopher-bonitz** [Textalk/websocket-php#42]
I'm using this client with the server from here https://github.com/nekudo/php-websocket in a specialized setup. (doing 3. party authentication integration inside the handshake process of websockets.

I noticed that the handshake headers are all in lowercase, and in my case the server does not support that.
Doing a quick read on the spec from https://tools.ietf.org/html/rfc6455 I haven't been able narrow down if this is in the specification, but they do spell the header names with some upper case letters.

So I assume it is "more correct" to do use a case sensitive approach, although it might be optional in the docs. 

I have done a "case sensivity" fix allowing me to use the project with nekudu websocket.
Line 107 in client.php 
`
      $headers = array(
      'Host'                  => $host . ":" . $port,
      'User-agent'            => 'websocket-client-php',
      'Connection'            => 'Upgrade',
      'Upgrade'               => 'websocket',
      'Sec-WebSocket-Key'     => $key,
      'Sec-WebSocket-Version' => '13',
    );
`

**Comment by dmromanov** [comment]
RFC6455 (Websocket) defines [headers as in RFC2616](https://tools.ietf.org/html/rfc6455#section-4.1). And the RFC2616 states the headers [to be case-insensitive](https://tools.ietf.org/html/rfc2616#section-4.2).
So the error is not in this project, but in `nekudo/php-websocket`.

**Comment by cb-dtf** [comment]
Woaw, that was some nice digging you did there.

I have noticed that the nekudo/php-websocket uses Upper case now.
https://github.com/nekudo/php-websocket/blob/master/client/lib/class.websocket_client.php

I'm not really a git or github specialist, so honestly I'm not sure if this could be solved by simply pulling in the latest changes and just sync the project. 

Question is of cause if that would require someone to do some merging work, would kind of expect that.

**Comment by kensoh** [comment]
Sounds like if the nekudo project uses uppercase while current repo uses lowercase there will still be conflict. Actually since current repo is not often updated, your solution of fixing by making a local change is an ideal solution to make the two together. Unless the nekudo repo you can raise an issue to tell them to follow standards lol in future releases.

**Comment by atyachin** [comment]
Note: if you're passing customized headers and would like to keep case sensitivity, you also need to modify line 126 in Client.php:
`$headers = array_merge($headers, array_change_key_case($this->options['headers']));`
to:
`$headers = array_merge($headers, $this->options['headers']);`
