### ISSUE TITLE
guide to Laravel? Not really an issue

### ISSUE THREAD

**Issue by mooseh** [Textalk/websocket-php#43]
Hi There

Could you give an install guide for laravel as this seems to be the framework of choice these days,
as laravel does the auto loading would be super helpful thanks :)

**Comment by mcordingley** [comment]
There's nothing different in the way you do it. Just add it to composer as a dependency and start using, as documented.

**Comment by razava** [comment]
Hi!
installed in laravel 5.2 and client work. but i don't know how to start and configuration server? how to use pusher? Thanks to instruct me....

**Comment by kensoh** [comment]
Just found out about this cool project today.. This repo is more for websocket client and the server portion is not yet fully developed for production use at current state, I believe, from the readme and browsing through the code.

**Comment by kensoh** [comment]
Adding on, without autoloading or composer this project can also be used. I just discovered this great project today and using it to communicate with chrome browser through websocket.

```php
<?php

require('ws/Base.php');
require('ws/Client.php');
require('ws/Exception.php');
require('ws/BadOpcodeException.php');
require('ws/BadUriException.php');
require('ws/ConnectionException.php');
use WebSocket\Client;

$client = new Client("ws://localhost:9222/devtools/page/f0a5c2e0-ba2f-4be2-80ec-6299cfcf88c8");
$client->send('{"id":1,"method":"Page.navigate","params":{"url":"http://tebel.org/index_mobile.php"}}');
echo $client->receive() . "\n";

?>
```
