### ISSUE TITLE
How to set Sec-WebSocket-Protocol

### ISSUE THREAD

**Issue by dimmu311** [Textalk/websocket-php#53]
i try to use websocket-php to connect to a loxone miniserver.
they say in the api to specify Sec-WebSocket-Protocol -> remotecontrol​ when connecting.

so is ist possible so set a Sec-WebSocket-Protocol?

thanks

**Comment by sirn-se** [comment]
Yes, by using the `headers` option.

```php
$client = new Client($url, ['headers' => ['Sec-WebSocket-Protocol' => 'remotecontrol']]);
```
