### ISSUE TITLE
WebSocket\ConnectionException: Could not open socket

### ISSUE THREAD

**Issue by BLOKKT** [Textalk/websocket-php#56]
Hello. I am running this within my Laravel project (server nginx) and here is my issue.
`WebSocket\ConnectionException: Could not open socket to "127.0.0.1:8080": Connection refused (111). in /home/forge/project/vendor/textalk/websocket/lib/Client.php:95`

and if I change from 127.0.0.1 to 1.0.0.127 I get timeout (110) 

Sorry for bad english

**Comment by nahkampf** [comment]
Well, is your nginx configured correctly? Do you have something to actually connect to on 127.0.0.1:8080 ? 

You might know this already but: 127.0.0.1 is your loopback interface, ie meaning localhost. 1.0.0.127 is an ip owned by CloudFlare.

**Comment by BLOKKT** [comment]
Sorry I should have explained in more detail.
I'm not sure if my nginx is configured correctly, I am new to setting these things up. What would be the best way to set it up for this? This issue also persists on apache.

**Comment by nahkampf** [comment]
@BLOKKT check this config out and adjust to taste https://gist.github.com/uorat/10b15a32f3ffa3f240662b9b0fefe706
