### ISSUE TITLE
Help me....Why is it pending for?

### ISSUE THREAD

**Issue by tianxionglu** [Textalk/websocket-php#58]
**my php code..**
**always pending....
why????**
**help me!please....**
`<?php

require('../vendor/autoload.php');

use WebSocket\Client;
ini_set("max_execution_time", "3600");
$client = new Client("ws://127.0.0.1:9503");
$client->send("Hello from PHP");
echo $client->receive() . "\n"; // Should output 'Hello from PHP'`

**Comment by bkdotcom** [comment]
stupid question:  can you confirm it's connecting?

is anything after `new Client` being executed?
