### ISSUE TITLE
feature request:  Client destructor - option to keep socket open

### ISSUE THREAD

**Issue by bkdotcom** [Textalk/websocket-php#63]
https://github.com/Textalk/websocket-php/blob/master/lib/Client.php#L37

`class Client extends Base`

```PHP
class Base {

  public function __destruct() {
    if ($this->socket) {
      if (get_resource_type($this->socket) === 'stream') fclose($this->socket);
      $this->socket = null;
    }
  }

}
```

`PHP Warning:  fwrite() expects parameter 1 to be resource, null given in vendor/textalk/websocket/lib/Base.php on line 251`

`PHP Fatal error:  Uncaught exception 'WebSocket\ConnectionException' with message 'Could only write  out of 557 bytes.' in vendor/textalk/websocket/lib/Base.php:256`

I have encountered an object destructing and attempting to send a message after WebSocket/Client's destructor (It's an Error notification system)..   

would be nice to have a `'destruct' : false` (default: true) option to not close the socket / don't set to null in __destruct

```PHP
  public function __destruct() {
    if ($this->options['destruct'] && $this->socket) {
      if (get_resource_type($this->socket) === 'stream') fclose($this->socket);
      $this->socket = null;
    }
  }
```

**Comment by sirn-se** [comment]
If the Client is destructed, it will not be available for send/receive anyhow. So this really doesn't make any sense. Closing.
