### ISSUE TITLE
failed: Server sent invalid upgrade response

### ISSUE THREAD

**Issue by asdfghjk16945** [Textalk/websocket-php#71]
在服务器中连接wss报错。failed: Server sent invalid upgrade response

**Comment by sirn-se** [comment]
Please post a code snippet that reproduces this issue, then I can have a look at it.

**Comment by scaleman114** [comment]
I have the same problem using:
public function SendCommand()
    {
        $client = new Client("ws://xxx.xxx.xxx.xxx:4101");
        $arrayToSend = [
            'COMMAND' => 'DBINFO',
            'TABLE' => 'WEIGHMENTS',
            'PARAM' => 'COUNT',
        ];
        $client->send(json_encode($arrayToSend));
        echo $client->receive();
    }

If I use the google Simple Websocket Client or Javascript it works perfectly.

**Comment by sirn-se** [comment]
The error implies that the server responded in a way the client did not expect.

To be able to look into this, we need a code snippet that **reproduces** this error, or at least a **log dump** of sent/received data of the handshake operation.

**Comment by scaleman114** [comment]
Thanks for the reply. I have sorted this now. The server didn't like:
'Upgrade' => 'websocket',
it required
'Upgrade' => 'WebSocket',

**Comment by sirn-se** [comment]
Ok, the issue was with the server then. Closing this.
