### ISSUE TITLE
Any option to simulate in one env?

### ISSUE THREAD

**Issue by andrew-svirin** [Textalk/websocket-php#85]
I wanted to make some local tests for socket works and found that message `pong` sent for response on message `ping` also coming to the same stream and server think that `pong` is also came from client, but it is incorrect.

**Comment by andrew-svirin** [comment]
Also i do not understand how works `$client->close()` if i have next server from example

```php
        while ($server->accept()) {
            try {
                while (true) {
                    $message = $server->receive();

                    if ($message === 'ping') {
                        $server->send('pong', 'ping', true);
                    } elseif ($auth = $server->getHeader('Authorization')) {
                        $server->send("$auth - $message", 'text', false);
                    } else {
                        $server->send($message, 'text', false);
                    }
                }
            } catch (\WebSocket\ConnectionException $e) {
                \Illuminate\Support\Facades\Log::error($e);
            }
        }
```

**Comment by andrew-svirin** [comment]
Ok. Thanks. I did server from [example](https://github.com/Textalk/websocket-php/blob/master/examples/echoserver.php)

**Comment by andrew-svirin** [comment]
@sirn-se could you suggest, how can i send response from server to specific clients connected to socket? Is it possible at all?

**Comment by sirn-se** [comment]
@andrew-svirin The Server is single stream. So no, it's not possible to separate connected clients.
