### ISSUE TITLE
Verify that stream_socket_client function is available / enabled in client

### ISSUE THREAD

**Issue by MasterOdin** [Textalk/websocket-php#93]
We had a developer integrating this library into a larger project, and they were hitting a `ConnectionException` with the message about not being able to connect to the given host/port, but that the `$errno` and `$errstr` that were supposed to be printed out were blank. They did not know what to do as connecting to the client via python / JS was working fine. As it turns out, the project had set-up a disabled PHP functions list that included `stream_socket_client` which was causing the function to silently fail with no error.

To help others, would it be helpful to check (either within constructor or at global scope above class definition) that `stream_socket_client` is not disabled, doing something like:

```php
if (!function_exists('stream_socket_client')) {
    throw new Exception('stream_socket_client is disabled');
}
```

Happy to open a PR for this if desired (with clarification as to where such a check might live), though not sure how one might write a unit test for it.

**Comment by sirn-se** [comment]
I suppose it fails silently because we use `@` before function name. Maybe we need some other strategy to handle those kind of errors.

In theory, any internal function can be disabled. Creating a long list of functions to check isn't a good idea, I believe. It would be better to improve the error handling, so it doesn't suppress important errors.

**Comment by MasterOdin** [comment]
Fail silently was the wrong phrase as the library does issue an error, it's just that the error is `Could not open socket to "localhost:12345":  ().`, which our developer found confusing to debug.

I think for here, I would propose editing https://github.com/Textalk/websocket-php/blob/master/lib/Client.php#L108-L112 to be something like:

```php
        if (!$this->isConnected()) {
            if (!function_exists('stream_socket_client')) {
                $errstr = "stream_socket_client function is disabled";
            }
            throw new ConnectionException(
                "Could not open socket to \"$host:$port\": $errstr ($errno)."
            );
        }
```

and maybe a similar check around https://github.com/Textalk/websocket-php/blob/master/lib/Server.php#L39.
